# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 21b9f75413741b9ef8a63b1579fd31d3198f498e4d1f102e1e2020b01715dfb197e637749f4cdbd998d782ba63df346082302a69564f9cc4121eedaf5f90db29

test:
  secret_key_base: 74fa7a0eb0a7c2bcf9a663143c6320ba736a9fbe0793d5c7f95d3778d8d1b8a9f38d23fd46e1869f84d42f7690a9571d309af8409f5d9302e936c6a096a087b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
